# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

#cuda 7.5 #ssd
export PATH=/export/home/xxx/cuda-7.5/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/export/home/xxx/cuda-7.5/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/export/home/xxx/caffe-ssd/build/lib

# User specific aliases and functions
export LD_LIBRARY_PATH=/export/opencv320/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

alias vi='vim'

# added by Anaconda2 4.4.0 installer
export PATH="/export/home/xxx/anaconda2/bin:$PATH"
